// <auto-generated />
namespace autobase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddVehicleRequests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVehicleRequests));
        
        string IMigrationMetadata.Id
        {
            get { return "202605221129333_AddVehicleRequests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
